DELETE FROM statistic_files;
DELETE FROM inventory_actions;
DELETE FROM inventories;
DELETE FROM warehouses;
DELETE FROM products_categories;
DELETE FROM products;
DELETE FROM categories;
DELETE FROM users_role_types;
DELETE FROM users;